name: Publish Nuget Package - S2kDesignTemplate.ApiExtensions

# Run workflow on every push to the main branch
on:
  push:
    branches: [ main ]

jobs:
  publish-nuget-package:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
    
    # sets up .NET Core SDK 5.0.101
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101

    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet build src/ApiExtensions/S2kDesignTemplate.ApiExtensions.csproj -c Release /p:AssemblyVersion=1.0.0.${{ github.run_number }} /p:Version=1.0.0.${{ github.run_number }}

    - name: Setup NuGet.exe for use with actions
      # You may pin to the exact commit or the version.
      # uses: NuGet/setup-nuget@04b0c2b8d1b97922f67eca497d7cf0bf17b8ffe1
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-api-key: ${{secrets.NUGET_API_KEY}}
        nuget-api-key-source: Github

    - name: Publish .NET Core Project
      run: nuget push src/ApiExtensions/bin/Release/S2kDesignTemplate.ApiExtensions.1.0.0.${{ github.run_number }}.nupkg -Source Github