name: Publish Nuget Package 

# Run workflow on every push to the main branch
on:
  push:
    branches: [ main ]

jobs:
  publish-nuget-package:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
    
    # sets up .NET Core SDK 5.0.101
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101

    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet build src/ApiExtensions/S2kDesignTemplate.ApiExtensions.csproj -c Release /p:AssemblyVersion=1.0.0.${{ github.run_number }} /p:Version=1.0.0.${{ github.run_number }}
      
    - name: Push To Github
      run: dotnet nuget push src/ApiExtensions/bin/Release/S2kDesignTemplate.ApiExtensions.1.0.0.${{ github.run_number }}.nupkg --source https://nuget.pkg.github.com/s2kdesign-com/index.json --api-key ${{secrets.NUGET_API_KEY}}
      env:
        GITHUB_TOKEN: ${{secrets.NUGET_API_KEY}}